export default Object.freeze({
  ALERT_FREQUENCY: 'ALERT_FREQUENCY',
  INTERVAL_ID: 'INTERVAL_ID',
  IS_TIMER_GRANTED: 'IS_TIMER_GRANTED',
  LAST_NOTIFICATION_TIME: 'LAST_NOTIFICATION_TIME',
  LOCATIONS: 'LOCATIONS',
  TIME_DURATION: 'TIME_DURATION',
  WASH_FREQUENCY: 'WASH_FREQUENCY',
});
